import "server-only";

import {randomUUID} from "node:crypto";

import {DEFAULT_SITE_SETTINGS, SITE_SETTINGS_SINGLETON_KEY} from "@/lib/types/site-settings";
import type {
  AvailabilityStats,
  CheckRequestTemplateRow,
  HistorySnapshotRow,
  GroupInfoRow,
  SiteSettingsRow,
  SystemNotificationRow,
} from "@/lib/types/database";

import type {AdminUserRecord, StoredCheckConfigRow} from "./types";

type LooseRow = Record<string, unknown>;

export const POSTGRES_CONTROL_PLANE_SCHEMA_STATEMENTS = [
  `
    CREATE TABLE IF NOT EXISTS admin_users (
      id uuid PRIMARY KEY,
      username text NOT NULL UNIQUE,
      password_hash text NOT NULL,
      last_login_at timestamptz,
      created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
      updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
    )
  `,
  `
    CREATE TABLE IF NOT EXISTS check_request_templates (
      id uuid PRIMARY KEY,
      name text NOT NULL UNIQUE,
      type text NOT NULL,
      request_header jsonb,
      metadata jsonb,
      created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
      updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
    )
  `,
  `
    CREATE TABLE IF NOT EXISTS check_configs (
      id uuid PRIMARY KEY,
      name text NOT NULL,
      type text NOT NULL,
      model text NOT NULL,
      endpoint text NOT NULL,
      api_key text NOT NULL,
      enabled boolean NOT NULL DEFAULT true,
      is_maintenance boolean NOT NULL DEFAULT false,
      template_id uuid REFERENCES check_request_templates(id) ON DELETE SET NULL,
      request_header jsonb,
      metadata jsonb,
      group_name text,
      created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
      updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
    )
  `,
  `CREATE INDEX IF NOT EXISTS idx_check_configs_template_id ON check_configs (template_id)`,
  `
    CREATE TABLE IF NOT EXISTS group_info (
      id uuid PRIMARY KEY,
      group_name text NOT NULL UNIQUE,
      website_url text,
      tags text NOT NULL DEFAULT '',
      created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
      updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
    )
  `,
  `
    CREATE TABLE IF NOT EXISTS system_notifications (
      id uuid PRIMARY KEY,
      message text NOT NULL,
      is_active boolean NOT NULL DEFAULT true,
      level text NOT NULL DEFAULT 'info',
      created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
    )
  `,
  `
    CREATE TABLE IF NOT EXISTS site_settings (
      singleton_key text PRIMARY KEY CHECK (singleton_key = 'global'),
      site_name text NOT NULL,
      site_description text NOT NULL,
      site_icon_url text NOT NULL DEFAULT '/favicon.png',
      hero_badge text NOT NULL,
      hero_title_primary text NOT NULL,
      hero_title_secondary text NOT NULL,
      hero_description text NOT NULL,
      footer_brand text NOT NULL,
      admin_console_title text NOT NULL,
      admin_console_description text NOT NULL,
      created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
      updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
    )
  `,
] as const;

export const POSTGRES_RUNTIME_SCHEMA_STATEMENTS = [
  `
    CREATE TABLE IF NOT EXISTS check_history (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      config_id uuid NOT NULL REFERENCES check_configs(id) ON DELETE CASCADE,
      status text NOT NULL,
      latency_ms integer,
      ping_latency_ms double precision,
      checked_at timestamptz NOT NULL,
      message text,
      created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
      CONSTRAINT check_history_status_valid CHECK (
        status IN ('operational', 'degraded', 'failed', 'validation_failed', 'maintenance', 'error', 'pending')
      ),
      CONSTRAINT check_history_latency_positive CHECK (latency_ms IS NULL OR latency_ms >= 0)
    )
  `,
  `CREATE INDEX IF NOT EXISTS idx_check_history_config_id ON check_history (config_id)`,
  `CREATE INDEX IF NOT EXISTS idx_check_history_checked_at ON check_history (checked_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_history_config_checked ON check_history (config_id, checked_at DESC)`,
] as const;

export const SQLITE_CONTROL_PLANE_SCHEMA_STATEMENTS = [
  `PRAGMA foreign_keys = ON`,
  `PRAGMA journal_mode = WAL`,
  `
    CREATE TABLE IF NOT EXISTS admin_users (
      id text PRIMARY KEY,
      username text NOT NULL UNIQUE,
      password_hash text NOT NULL,
      last_login_at text,
      created_at text NOT NULL,
      updated_at text NOT NULL
    )
  `,
  `
    CREATE TABLE IF NOT EXISTS check_request_templates (
      id text PRIMARY KEY,
      name text NOT NULL UNIQUE,
      type text NOT NULL,
      request_header text,
      metadata text,
      created_at text NOT NULL,
      updated_at text NOT NULL
    )
  `,
  `
    CREATE TABLE IF NOT EXISTS check_configs (
      id text PRIMARY KEY,
      name text NOT NULL,
      type text NOT NULL,
      model text NOT NULL,
      endpoint text NOT NULL,
      api_key text NOT NULL,
      enabled integer NOT NULL DEFAULT 1,
      is_maintenance integer NOT NULL DEFAULT 0,
      template_id text REFERENCES check_request_templates(id) ON DELETE SET NULL,
      request_header text,
      metadata text,
      group_name text,
      created_at text NOT NULL,
      updated_at text NOT NULL
    )
  `,
  `CREATE INDEX IF NOT EXISTS idx_check_configs_template_id ON check_configs (template_id)`,
  `
    CREATE TABLE IF NOT EXISTS group_info (
      id text PRIMARY KEY,
      group_name text NOT NULL UNIQUE,
      website_url text,
      tags text NOT NULL DEFAULT '',
      created_at text NOT NULL,
      updated_at text NOT NULL
    )
  `,
  `
    CREATE TABLE IF NOT EXISTS system_notifications (
      id text PRIMARY KEY,
      message text NOT NULL,
      is_active integer NOT NULL DEFAULT 1,
      level text NOT NULL DEFAULT 'info',
      created_at text NOT NULL
    )
  `,
  `
    CREATE TABLE IF NOT EXISTS site_settings (
      singleton_key text PRIMARY KEY CHECK (singleton_key = 'global'),
      site_name text NOT NULL,
      site_description text NOT NULL,
      site_icon_url text NOT NULL DEFAULT '/favicon.png',
      hero_badge text NOT NULL,
      hero_title_primary text NOT NULL,
      hero_title_secondary text NOT NULL,
      hero_description text NOT NULL,
      footer_brand text NOT NULL,
      admin_console_title text NOT NULL,
      admin_console_description text NOT NULL,
      created_at text NOT NULL,
      updated_at text NOT NULL
    )
  `,
] as const;

export const SQLITE_RUNTIME_SCHEMA_STATEMENTS = [
  `
    CREATE TABLE IF NOT EXISTS check_history (
      id integer PRIMARY KEY AUTOINCREMENT,
      config_id text NOT NULL REFERENCES check_configs(id) ON DELETE CASCADE,
      status text NOT NULL,
      latency_ms integer,
      ping_latency_ms real,
      checked_at text NOT NULL,
      message text,
      created_at text NOT NULL,
      CHECK (status IN ('operational', 'degraded', 'failed', 'validation_failed', 'maintenance', 'error', 'pending')),
      CHECK (latency_ms IS NULL OR latency_ms >= 0)
    )
  `,
  `CREATE INDEX IF NOT EXISTS idx_check_history_config_id ON check_history (config_id)`,
  `CREATE INDEX IF NOT EXISTS idx_check_history_checked_at ON check_history (checked_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_history_config_checked ON check_history (config_id, checked_at DESC)`,
] as const;

const DEFAULT_REQUEST_TEMPLATE_DEFINITIONS = [
  {
    id: "8e6d6289-b8c8-4b8e-90f6-96e51ec87f01",
    name: "OpenAI Yes/No Arithmetic",
    type: "openai",
  },
  {
    id: "8e6d6289-b8c8-4b8e-90f6-96e51ec87f02",
    name: "Anthropic Yes/No Arithmetic",
    type: "anthropic",
  },
  {
    id: "8e6d6289-b8c8-4b8e-90f6-96e51ec87f03",
    name: "Gemini Yes/No Arithmetic",
    type: "gemini",
  },
] as const;

export function createStorageId(): string {
  return randomUUID();
}

export function nowIso(): string {
  return new Date().toISOString();
}

export function serializeJson(value: Record<string, unknown> | null | undefined): string | null {
  if (!value) {
    return null;
  }

  return JSON.stringify(value);
}

export function parseJsonObject<T extends Record<string, unknown>>(
  value: unknown
): T | null {
  if (!value) {
    return null;
  }

  if (typeof value === "string") {
    try {
      const parsed = JSON.parse(value) as unknown;
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
        return null;
      }
      return parsed as T;
    } catch {
      return null;
    }
  }

  if (typeof value === "object" && !Array.isArray(value)) {
    return value as T;
  }

  return null;
}

function toOptionalString(value: unknown): string | null {
  if (value === null || value === undefined) {
    return null;
  }

  if (value instanceof Date) {
    return value.toISOString();
  }

  if (typeof value === "string") {
    return value;
  }

  return String(value);
}

function toRequiredString(value: unknown): string {
  return toOptionalString(value) ?? "";
}

function toOptionalNumber(value: unknown): number | null {
  if (value === null || value === undefined || value === "") {
    return null;
  }

  if (typeof value === "number") {
    return Number.isFinite(value) ? value : null;
  }

  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function toBoolean(value: unknown): boolean {
  if (typeof value === "boolean") {
    return value;
  }

  if (typeof value === "number") {
    return value !== 0;
  }

  if (typeof value === "string") {
    return value === "true" || value === "1";
  }

  return false;
}

export function getDefaultSiteSettingsRow(): SiteSettingsRow {
  const timestamp = nowIso();

  return {
    singleton_key: SITE_SETTINGS_SINGLETON_KEY,
    site_name: DEFAULT_SITE_SETTINGS.siteName,
    site_description: DEFAULT_SITE_SETTINGS.siteDescription,
    site_icon_url: DEFAULT_SITE_SETTINGS.siteIconUrl,
    hero_badge: DEFAULT_SITE_SETTINGS.heroBadge,
    hero_title_primary: DEFAULT_SITE_SETTINGS.heroTitlePrimary,
    hero_title_secondary: DEFAULT_SITE_SETTINGS.heroTitleSecondary,
    hero_description: DEFAULT_SITE_SETTINGS.heroDescription,
    footer_brand: DEFAULT_SITE_SETTINGS.footerBrand,
    admin_console_title: DEFAULT_SITE_SETTINGS.adminConsoleTitle,
    admin_console_description: DEFAULT_SITE_SETTINGS.adminConsoleDescription,
    created_at: timestamp,
    updated_at: timestamp,
  };
}

export function getDefaultRequestTemplateRows(): CheckRequestTemplateRow[] {
  const timestamp = nowIso();

  return DEFAULT_REQUEST_TEMPLATE_DEFINITIONS.map((template) => ({
    id: template.id,
    name: template.name,
    type: template.type,
    request_header: null,
    metadata: {
      checkCx: {
        challengeMode: "yes_no_arithmetic",
        promptInstruction:
          "Read the arithmetic statement and answer with ONLY yes or no in lowercase.",
        cases: [
          {expression: "1 + 1", claimedAnswer: 2, expectedAnswer: "yes"},
          {expression: "1 + 2", claimedAnswer: 4, expectedAnswer: "no"},
          {expression: "2 + 2", claimedAnswer: 4, expectedAnswer: "yes"},
          {expression: "3 - 1", claimedAnswer: 1, expectedAnswer: "no"},
        ],
      },
    },
    created_at: timestamp,
    updated_at: timestamp,
  }));
}

export function mapAdminUserRecord(row: LooseRow): AdminUserRecord {
  return {
    id: toRequiredString(row.id),
    username: toRequiredString(row.username),
    password_hash: toRequiredString(row.password_hash),
    last_login_at: toOptionalString(row.last_login_at),
    created_at: toOptionalString(row.created_at),
    updated_at: toOptionalString(row.updated_at),
  };
}

export function mapCheckConfigRow(row: LooseRow): StoredCheckConfigRow {
  return {
    id: toRequiredString(row.id),
    name: toRequiredString(row.name),
    type: toRequiredString(row.type),
    model: toRequiredString(row.model),
    endpoint: toRequiredString(row.endpoint),
    api_key: toRequiredString(row.api_key),
    enabled: toBoolean(row.enabled),
    is_maintenance: toBoolean(row.is_maintenance),
    template_id: toOptionalString(row.template_id),
    request_header: parseJsonObject<Record<string, string>>(row.request_header),
    metadata: parseJsonObject<Record<string, unknown>>(row.metadata),
    group_name: toOptionalString(row.group_name),
    created_at: toOptionalString(row.created_at) ?? undefined,
    updated_at: toOptionalString(row.updated_at),
  };
}

export function mapRequestTemplateRow(row: LooseRow): CheckRequestTemplateRow {
  return {
    id: toRequiredString(row.id),
    name: toRequiredString(row.name),
    type: toRequiredString(row.type),
    request_header: parseJsonObject<Record<string, string>>(row.request_header),
    metadata: parseJsonObject<Record<string, unknown>>(row.metadata),
    created_at: toOptionalString(row.created_at) ?? undefined,
    updated_at: toOptionalString(row.updated_at) ?? undefined,
  };
}

export function mapHistorySnapshotRow(row: LooseRow): HistorySnapshotRow {
  return {
    id: toRequiredString(row.id),
    config_id: toRequiredString(row.config_id),
    status: toRequiredString(row.status),
    latency_ms: toOptionalNumber(row.latency_ms),
    ping_latency_ms: toOptionalNumber(row.ping_latency_ms),
    checked_at: toRequiredString(row.checked_at),
    message: toOptionalString(row.message),
    name: toRequiredString(row.name),
    type: toRequiredString(row.type),
    model: toRequiredString(row.model),
    endpoint: toOptionalString(row.endpoint),
    group_name: toOptionalString(row.group_name),
  };
}

export function mapAvailabilityStatsRow(row: LooseRow): AvailabilityStats {
  return {
    config_id: toRequiredString(row.config_id),
    period: toRequiredString(row.period) as AvailabilityStats["period"],
    total_checks: toOptionalNumber(row.total_checks) ?? 0,
    operational_count: toOptionalNumber(row.operational_count) ?? 0,
    availability_pct: toOptionalNumber(row.availability_pct),
  };
}

export function mapGroupInfoRow(row: LooseRow): GroupInfoRow {
  return {
    id: toRequiredString(row.id),
    group_name: toRequiredString(row.group_name),
    website_url: toOptionalString(row.website_url),
    tags: toOptionalString(row.tags),
    created_at: toOptionalString(row.created_at) ?? undefined,
    updated_at: toOptionalString(row.updated_at) ?? undefined,
  };
}

export function mapNotificationRow(row: LooseRow): SystemNotificationRow {
  return {
    id: toRequiredString(row.id),
    message: toRequiredString(row.message),
    is_active: toBoolean(row.is_active),
    level: toRequiredString(row.level) as SystemNotificationRow["level"],
    created_at: toRequiredString(row.created_at),
  };
}

export function mapSiteSettingsRow(row: LooseRow): SiteSettingsRow {
  return {
    singleton_key: toRequiredString(row.singleton_key),
    site_name: toRequiredString(row.site_name),
    site_description: toRequiredString(row.site_description),
    site_icon_url: toRequiredString(row.site_icon_url) || DEFAULT_SITE_SETTINGS.siteIconUrl,
    hero_badge: toRequiredString(row.hero_badge),
    hero_title_primary: toRequiredString(row.hero_title_primary),
    hero_title_secondary: toRequiredString(row.hero_title_secondary),
    hero_description: toRequiredString(row.hero_description),
    footer_brand: toRequiredString(row.footer_brand),
    admin_console_title: toRequiredString(row.admin_console_title),
    admin_console_description: toRequiredString(row.admin_console_description),
    created_at: toOptionalString(row.created_at) ?? undefined,
    updated_at: toOptionalString(row.updated_at) ?? undefined,
  };
}
